#!/usr/bin/python3
import sys

def factorize(num):
    for i in range(2, num//2+1):
        if num % i == 0:
            return '{0}={1}*{2}'.format(num, i, num//i)
    return '{0} is prime!'.format(num)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: factors <file>')
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            print(factorize(num))

